language: python

notifications:
  email:
    recipients:
      - manodeep@gmail.com
      - rseikel@bigpond.com
    on_success: change
    on_failure: always

script:
  - find . -type f \( -iname \*.dat -o -iname \*.dati \) -exec awk '{if(NF > 1 && ($2 < 0 || $2 > 1.0)) print ARGV[1], NR, $2}' {} \;  | wc -l
  - find . -type f \( -iname \*.dat -o -iname \*.dati \) -exec wc -l {} \; |  awk '{if($1 <= 3) {print $0; exit 1;} }'
  - find . -type f \( -iname \*.dat -o -iname \*.dati \) -exec awk '{if((NR==1 && NF != 1) || (NR > 1 && NF != 2)) {print ARGV[1], NR, $0; exit 1;}}' {} \; 
